// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aamrowpmuamrrnynntux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhbXJvd3BtdWFtcnJueW5udHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTY3NTAsImV4cCI6MjA2NTQ3Mjc1MH0.h1h887s3L24sOwnRI930cGRnzNgEC8ieWKLV6nFfeEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);